name: ContractRPG
version: '${project.version}'
main: com.infinity3113.contractrpg.ContractRPG
api-version: 1.20
authors: [infinity3113]
description: A plugin for daily, weekly, and special contracts.
depend: [Citizens, Vault, MMOItems, MythicLib, MythicMobs]
softdepend:
  - PlaceholderAPI
commands:
  contract:
    description: Opens the contract GUI or reloads the plugin.
    usage: /contract [reload|reset] # Añadido 'reset'
    permission: contractrpg.use

permissions:
  contractrpg.use:
    description: Allows player to use /contract command.
    default: true
  contractrpg.reload:
    description: Allows player to use /contract reload.
    default: op
  # ¡NUEVO! Permiso para el reset
  contractrpg.admin.reset:
    description: Allows forcing a mission reset for testing.
    default: op
  # ===== PERMISO AÑADIDO =====
  contractrpg.command.placeholder:
    description: "Allows viewing the list of available placeholders."
    default: op