# Idioma del plugin. Debe coincidir con un archivo en la carpeta /lang (ej: "es", "en")
language: "es"

# ¡NUEVO! Sistema de Niveles
leveling:
  # Fórmula para la experiencia necesaria. Puedes cambiar el 250.
  # Con 250, Nivel 1->2 necesita 250 EXP, Nivel 2->3 necesita 500 EXP, etc.
  experience-base: 250

daily-missions:
  # ¿Cuántas misiones diarias se le ofrecerán al jugador para que elija?
  offered-amount: 4
  # ¿Cuántas de las misiones ofrecidas puede aceptar el jugador cada día?
  selectable-amount: 2
  # Si es 'true', las misiones diarias no completadas se eliminarán cuando se ofrezcan nuevas.
  reset-unfinished-on-new-offer: true

weekly-missions:
  # ¿Cuántas misiones semanales se le ofrecerán al jugador?
  offered-amount: 3
  # ¿Cuántas de las misiones semanales puede aceptar el jugador cada semana?
  selectable-amount: 1
  reset-unfinished-on-new-offer: true

# ¡NUEVO! Sección para misiones especiales
special-missions:
  offered-amount: 2
  selectable-amount: 1

# ID del NPC de Citizens que aceptará las entregas de contratos.
delivery-npc-id: -1

# --- Configuración de Almacenamiento ---
# Opciones disponibles: "yaml", "sqlite"
storage:
  type: "yaml"