name: ContractRPG
version: '1.0.0'
main: com.infinity3113.contractrpg.ContractRPG
api-version: 1.20
authors: [YourName]
description: A plugin for daily, weekly, and special contracts.
depend: [Citizens, Vault, MMOItems, MythicLib, MythicMobs]

commands:
  contract:
    description: Opens the contract GUI or reloads the plugin.
    usage: /contract [reload]
    permission: contractrpg.use

permissions:
  contractrpg.use:
    description: Allows player to use /contract command.
    default: true
  contractrpg.reload:
    description: Allows player to use /contract reload.
    default: op